// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwIx_V5hsIZtroMibyfAaJBPnnC3YFhNI',
    appId: '1:461402796120:web:12b033963fd5cdafcb1a2d',
    messagingSenderId: '461402796120',
    projectId: 'sub-manager-new',
    authDomain: 'sub-manager-new.firebaseapp.com',
    storageBucket: 'sub-manager-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7So3xoaTNf_Cp87-xNMR4Y3drrSXiljc',
    appId: '1:461402796120:android:077d47c0c2f0f3f4cb1a2d',
    messagingSenderId: '461402796120',
    projectId: 'sub-manager-new',
    storageBucket: 'sub-manager-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQL67D8UY2uiNTBZmE68Zh1xYhVyYteU',
    appId: '1:461402796120:ios:2465d9f6952ea098cb1a2d',
    messagingSenderId: '461402796120',
    projectId: 'sub-manager-new',
    storageBucket: 'sub-manager-new.firebasestorage.app',
    iosBundleId: 'com.example.projecktk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQL67D8UY2uiNTBZmE68Zh1xYhVyYteU',
    appId: '1:461402796120:ios:2465d9f6952ea098cb1a2d',
    messagingSenderId: '461402796120',
    projectId: 'sub-manager-new',
    storageBucket: 'sub-manager-new.firebasestorage.app',
    iosBundleId: 'com.example.projecktk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwIx_V5hsIZtroMibyfAaJBPnnC3YFhNI',
    appId: '1:461402796120:web:42ae536b8704a90fcb1a2d',
    messagingSenderId: '461402796120',
    projectId: 'sub-manager-new',
    authDomain: 'sub-manager-new.firebaseapp.com',
    storageBucket: 'sub-manager-new.firebasestorage.app',
  );

}